Increment
fishus/go-advanced-gophermart pull request #1
Opened 2024-02-15 19:12 UTC by fishus

2024-02-17 09:06 UTC, rktkov approved these changes

2024-03-01 10:00 UTC, rktkov approved these changes

2024-03-01 10:00 UTC, rktkov commented on internal/storage/storage.go
> +type UserStorager interface {
Во всех названиях методов в интерфейсах название сущности лишнее, потому что оно присутсвует в названии интерфейса.

2024-03-01 10:00 UTC, rktkov commented on internal/accrual/worker.go
> +				func() {
не пропушена ли здесь инструкция запуска go рутины?

2024-03-01 10:25 UTC, fishus commented on internal/accrual/worker.go
> +				func() {
@rktkov нет, это сделано намеренно с целью:

1. ограничить кол-во одновременных запросов к сервису расчёта баллов (сам воркер запускается в горутине (строка 17) и у меня есть настройка, которая регулирует кол-во запускаемых воркеров).
2. анонимная функция здесь сделана для упрощения вызова wg.Done через defer, т.к. несколько точек выхода.

2024-03-14 18:37 UTC, Perederey requested changes
проверил только часть, но пока думаю достаточно будет,

очень крутая работа, но отдаю на доработку, чтобы сделать еще лучше!

Завтра про архитектуру еще запишу

2024-03-14 18:37 UTC, Perederey commented on cmd/gophermart/main.go
> +		logger.Log.Error(err.Error())
забыл return?

2024-03-14 18:37 UTC, Perederey commented on cmd/gophermart/main.go
> +		logger.Log.Error(err.Error())
забыл retrun?

2024-03-14 18:37 UTC, Perederey commented on cmd/gophermart/main.go
> +	<-ctx.Done()
а что делаешь с context? Обработки-то нет

В твоем коде присутствует <-ctx.Done(), что указывает на ожидание завершения контекста. Это означает, что при получении сигнала отмены контекста программа завершит свою работу. Однако необходимо убедиться, что ты все корректоно закрыл, посмотри пример на chi  https://github.com/go-chi/chi/tree/master/_examples/graceful

2024-03-14 18:37 UTC, Perederey commented on internal/accrual/accrual_test.go
> +func (ts *LoyaltyTestSuite) setServiceOrder(s service.Orderer) {
тут хочется, чтобы ты проверял не только позитивные кейсы, но также и негативные, когда возникает ошибка

2024-03-14 18:37 UTC, Perederey commented on internal/accrual/add.go
> +		}
хороший кусок кода

2024-03-14 18:37 UTC, Perederey commented on internal/accrual/errors.go
> +var ErrMaxAttemptsReached = errors.New("maximum number of attempts has been reached")
если ошибки просто string, я бы их объявлял там, где они у тебя есть.

2024-03-14 18:37 UTC, Perederey commented on internal/accrual/worker.go
> +func (d *daemon) workerRequestOrderAccrual(ctx context.Context) {
похожий код у тебя уже был, может быть как-то сделать generic функцию для обработки и не дублировать код?

2024-03-14 18:37 UTC, Perederey commented on internal/accrual/worker.go
> +							err = d.service.Order().UpdateStatus(ctx, order.ID, models.OrderStatusProcessing)
перемудрил,

сделай лучше что у тебя Error это структура и на основе нее выводи ошибку. По факут default у тебя олтичается не так сильно от обычного. Просто у ошибки может быть свойство как процессить заказ и тогда никаких swith тебе не нужно, распаковываешь ошибку и все.

2024-03-14 18:37 UTC, Perederey commented on internal/accrual/worker.go
> +							err = d.service.Order().UpdateStatus(ctx, order.ID, models.OrderStatusProcessing)
сокртишь штук 100 lines кода

2024-03-14 18:37 UTC, Perederey commented on internal/accrual/worker.go
> +		}
опять перемудрил, очень много switch ни на что.
Один if на ok и unwrap ошибки на все остальное

2024-03-14 18:37 UTC, Perederey commented on internal/accrual/worker.go
> +	d.delay.Store(false)
мудрено, надо упрастить. Зачем тебе тут такая сложная контрукция? и зачем тебе delay?

2024-03-14 18:37 UTC, Perederey commented on internal/api/loyalty/api_test.go
> +
можно и так, но можно роуты и подгружать

2024-03-14 18:37 UTC, Perederey commented on internal/api/loyalty/balance.go
> +			f, _ := balance.Current.Float64()
проверку на ошибки нет, а надо делать
и _ := второй аргумент тут же лишний получается.

2024-03-14 18:37 UTC, Perederey commented on internal/api/loyalty/withdraw.go
> +	w.WriteHeader(http.StatusOK)
про ошибки нсова тоже самое
делаешь кастомную ошибку, где хранишь status от ошибки и делаешь unwrap - и снова меньше кода)

2024-03-14 18:37 UTC, Perederey commented on internal/api/loyalty/withdraw_test.go
> +			ts.Equal(tc.respStatus, resp.StatusCode())
мало проверки, надо бы еще проверить и response сам

2024-03-14 18:37 UTC, Perederey commented on internal/api/loyalty/withdrawals.go
> +	defer r.Body.Close()
где читаешь, там и делаешь r.Body.Close - а так получается, что где его еще нет, ты уже сразу его вывел

2024-03-14 18:37 UTC, Perederey commented on internal/api/loyalty/withdrawals_test.go
> +			if tc.respStatus == http.StatusOK {
в тестах так нельзя, это уже логика, делашешь просто ts.Require.Equal() ине двигаешься дальше просто по тесту

2024-03-14 18:37 UTC, Perederey commented on internal/api/order/add.go
> +		if errors.As(err, &validErr) {
перемудрил в errors, съедает очень много кода

2024-03-14 18:37 UTC, Perederey commented on internal/api/order/add.go
> +	}
тут не совсем понятно, почему у тебя daemon вызывается с новым context? Он тут тожно нужен? Может быть быть просто его спрять в daemon?
и попробуй избавиться от else https://github.com/uber-go/guide/blob/master/style.md - redundant else

2024-03-14 19:31 UTC, fishus commented on internal/accrual/accrual_test.go
> +func (ts *LoyaltyTestSuite) setServiceOrder(s service.Orderer) {
Тут не понял, т.к. в этом файле только настройка test suite для пакета и доп. методы для тестов, а все тесты в других файлах. Стараюсь делать и негативные проверки.

2024-03-14 19:31 UTC, fishus commented on internal/accrual/add.go
> +		}
Спасибо.

2024-03-14 19:36 UTC, fishus commented on internal/accrual/errors.go
> +var ErrMaxAttemptsReached = errors.New("maximum number of attempts has been reached")
@Perederey 
Не понял, что именно требуется: возвращать сразу строковую ошибку без объявления переменной?
Но я объявляю переменную, т.к. потом сравниваю полученную ошибку.
Или не собирать все ошибки пакета в одном месте?

2024-03-14 19:47 UTC, fishus commented on internal/accrual/worker.go
> +func (d *daemon) workerRequestOrderAccrual(ctx context.Context) {
Здесь у меня разделение логики. Отдельно общаемся с внешним api (requestOrderAccrual с ретраями), разбирая ответы от api, возвращая структуру.
И отдельно сам воркер (workerRequestOrderAccrual), задача которого получить order из канала отправить его в обработку (requestOrderAccrual ) и сохранить полученный ответ.
Дублированного кода не увидел.
Если речь о статусах, это сделанно намеренно, чтобы не смешивать обработку ответов http и бизнес-логику обработки полученных ответов от внешнего сервиса.
В requestOrderAccrual мы реализуем только обработку ответов от внешнего сервиса.
А в workerRequestOrderAccrual логика работы со статусами заказа на нашей стороне (менять ли статус в бд или начислять баллы и т.п.).

2024-03-14 19:55 UTC, fishus commented on internal/accrual/worker.go
> +		}
Тут в switch обрабатываются разные ответы от внешнего api. Не очень понимаю, как это можно заменить на unwrap ошибки, если ошибки нет.
С "ни на что" не соглашусь. Кроме OK требуется обработка StatusTooManyRequests с ретраями. А также на всякий случай обработка StatusNoContent (вдруг в нам по бизнес-логике потребуется сохранять его с отдельным статусом или как-то обрабатывать этот кейс?).

2024-03-14 19:59 UTC, fishus commented on internal/accrual/worker.go
> +	d.delay.Store(false)
@Perederey delay нужен для ретраев, т.к. мы обрабатываем ответ сервера StatusTooManyRequests и стопим все запросы к внешнему апи.
а сложная конструкция с ticker по 100ms нужна для того, чтобы по shutdown выйти до окончания "спячки". Иначе придётся ждать, пока спячка не закончится. А зачем ждать, если всё-равно программа завершается?

2024-03-14 20:07 UTC, fishus commented on internal/api/loyalty/balance.go
> +			f, _ := balance.Current.Float64()
Тут нет обработки ошибок, потому что второй аргумент это exact bool при приведении decimal к типу float64 при выводе баланса пользователя. Заменил на другую функцию.

2024-03-14 20:18 UTC, fishus commented on internal/api/loyalty/withdraw_test.go
> +			ts.Equal(tc.respStatus, resp.StatusCode())
@Perederey я проверяю код ответа, т.к. в случае ОК тело ответа пустое, а в случае ошибки значение имеет только код ответа. В данном роуте проверять кроме кода ответа нечего. В других роутах, где возвращается ответ я его проверяю.
Прошу уточнить, что еще из response в данном роуте требуется проверять?

2024-03-14 20:27 UTC, fishus commented on internal/api/loyalty/withdrawals_test.go
> +			if tc.respStatus == http.StatusOK {
@Perederey 
В данном случае проверка не кода ответа сервера, а проверка положительный тест кейс или негативный.
Собственно, в положительном тест кейсе нам нужно проверить и тело ответа. А в негативных проерках проверяется только код ответа.

2024-03-14 20:35 UTC, fishus commented on internal/api/order/add.go
> +	}
Потому что здесь функция демона (для добавления заказа в канал воркера) вызывается в хендлере http сервера, соотв-но здесь можно получить только контекст запроса, у которого может быть таймаут.
Поэтому создаю новый контекст. Если можно как-то получить родительский контекст приложения, то прошу показать как.
На самом деле сейчас внутри функции AddNewOrder контекст не используется, это заделка на будущее.

2024-03-14 20:44 UTC, fishus commented on internal/api/loyalty/withdrawals.go
> +	defer r.Body.Close()
Точно, нет необходимости закрывать request body в хендлерах, т.к. это сделает http.server

2024-03-14 20:59 UTC, fishus commented on internal/api/loyalty/withdraw.go
> +	w.WriteHeader(http.StatusOK)
Как я могу вернуть одну ошибку, если сервис мне возвращает разные ошибки (ErrLowBalance / ErrOrderWrongNum)? Зачем слою бизнес логики возвращать http статус в ошибке?
Тут логика какая: в слое бизнес-логики происходит проверка перед или во время списания средств и возвращается какая-то ошибка.
В зависимости от этой ошибки я уже возвращаю http-код ответа. Ошибки логически разные и ответы http разные, в зависимости от ошибки.
Слой бизнес логики вобще не должен ничего знать про http статусы. 
Прошу привести пример как это можно улучшить.

2024-03-14 21:50 UTC, fishus commented on internal/accrual/worker.go
> +							err = d.service.Order().UpdateStatus(ctx, order.ID, models.OrderStatusProcessing)
Исправил

2024-03-16 17:57 UTC, merged